name: Hello World Workflow

on:
  push:
    branches:
      - '**'

jobs:
  hello-world:
    name: Hello World Jobb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Say Hello World
        run: echo "Hello, World!"
