name: Terraform S3 Bucket Creation

on:
  push:
    branches:
      - feature/setup-github-terraform-s3-bucket



jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps: 
       - name: 'Configure AWS Credentials'
         run: echo "AWS credentials configured"
